server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingminghua/orderingsystem.git #Git 仓库地址
          searchPaths: configfile #仓库路径
          username: mingminghua #Git 仓库用户名
          password: huamingming12 #Git 仓库密码
      #label: master #仓库的分支
      label: master

  #        native:
#          search-locations:file:///C:/Users/Adminstrator/IdeaProjects/orderingsystem/configfile
  profiles:
    bus:
      trace:
        enable: true
#    active: native
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


