server:
  port: 8040
spring:
  application:
    name: order-dev
  datasource:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/orderingsystem?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: Hua@201711
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sourthwind.entity